export const START_QUIZ = 'START_QUIZ'
export const TIME_OUT = 'TIME_OUT'
export const QUIZ_NEXT = 'QUIZ_NEXT'
export const QUIZ_SUBMIT = 'QUIZ_SUBMIT'
export const QUIZ_SHOW_ANSWER = 'QUIZ_SHOW_ANSWER'
export const TIMER_COUNT_DOWN = 'TIMER_COUNT_DOWN'
export const RANDOM_QUESTIONS = 'RANDOM_QUESTIONS'


