export { default as ActiveRecently } from './ActiveRecently'
export { default as BannerContent } from './BannerContent'
export { default as CourseDetails } from './CourseDetails'
export { default as CourseOverview } from './CourseOverview'
export { default as RelatedCourses } from './RelatedCourses'
export { default as News } from './NewsOfCourse'
